version: 2
updates:
  - package-ecosystem: swift
    directory: /GymBroPackage
    schedule:
      interval: weekly
    commit-message:
      prefix: chore
    groups:
      pointfree:
        patterns:
          - "*pointfree*"
          - "swift-*"
          - "sqlite-data"
          - "combine-schedulers"
          - "xctest-dynamic-overlay"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    commit-message:
      prefix: chore
